#!/usr/bin/env python3
"""EAMOS intake — the source-reorganization primitive (RFC-0002 §6; RFC-0001 §15-M5).

Dependency-free (stdlib + yamlmini). The foundational half of intake: ingest provided material and
**normalize it into the typed inputs ledger** — dedupe, tag by source, mark every cell `sourced` —
so the manifest's numbers come from material, never hand-entry. The output is a paste-ready
`inputs:` block (RFC-0001 §6). Connectors (Jira / Notion / Sheets) and a foreign-deck extractor are
later additions; the structured sources here are a **pasted KPI table** (CSV) and the **prior
instance** (the series store — the prior deck's data, RFC-0001 §9).

    python tools/intake.py --csv examples/intake/q3-kpis.csv --series build/series.json --out build/ledger.yaml

Dedup rule: the **current** source (CSV) wins over the prior one (series); prior fills gaps. Every
emitted cell is `provided: true, provenance: sourced` — assumed values are added later, by hand,
only where material is genuinely missing (RFC-0001 §6).
"""

import argparse
import csv
import json
import os
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS)
import yamlmini  # noqa: E402  (unused now, kept for symmetry / future YAML sources)  # noqa: F401


def _titleize(key):
    return key.split(".", 1)[-1].replace("_", " ").replace("-", " ").strip().capitalize()


def from_csv(path):
    """A pasted/exported KPI table -> cells. Header (case-insensitive): key,value[,label,source]."""
    cells = {}
    with open(path, encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        norm = {(k or "").strip().lower(): k for k in (reader.fieldnames or [])}
        if "key" not in norm or "value" not in norm:
            raise ValueError(f"{path}: CSV needs at least 'key' and 'value' columns")
        for row in reader:
            key = (row[norm["key"]] or "").strip()
            if not key:
                continue
            cells[key] = {
                "label": (row.get(norm.get("label", ""), "") or "").strip() or _titleize(key),
                "value": (row[norm["value"]] or "").strip(),
                "source": (row.get(norm.get("source", ""), "") or "").strip() or f"{os.path.basename(path)} (pasted table)",
                "via": "intake/csv",
            }
    return cells


def from_series(path):
    """The prior instance's KPIs (the series store, RFC-0001 §9) -> cells (the prior deck's data)."""
    if not os.path.exists(path):
        return {}
    store = json.load(open(path, encoding="utf-8"))
    series_id = store.get("series_id", "series")
    instances = store.get("instances", []) or []
    cells = {}
    for key, hist in (store.get("kpi_history", {}) or {}).items():
        prior = next((i for i in reversed(instances) if i in hist), None)
        if prior is None:
            continue
        cells[key] = {"label": _titleize(key), "value": str(hist[prior]),
                      "source": f"prior instance {series_id}@{prior}", "via": "intake/series"}
    return cells


def reorganize(csv_paths, series_path):
    """Merge sources into one normalized ledger. Current (CSV) wins; prior (series) fills gaps."""
    ledger, prov = {}, {"overridden": 0, "gap_filled": 0}
    prior = from_series(series_path) if series_path else {}
    for key, cell in prior.items():
        ledger[key] = cell
    for path in csv_paths or []:
        for key, cell in from_csv(path).items():
            if key in ledger:
                prov["overridden"] += 1
            ledger[key] = cell                       # current source wins (dedupe)
    prov["gap_filled"] = sum(1 for k, c in ledger.items() if c["via"] == "intake/series")
    return ledger, prov


def emit_yaml(ledger):
    out = ["# Generated by intake.py — paste into a manifest's `inputs:` (RFC-0001 §6). Zero hand-entry.",
           "inputs:"]
    for key in sorted(ledger):
        c = ledger[key]
        out.append(f"  {key}:")
        out.append(f'    label: "{c["label"]}"')
        out.append(f'    value: "{c["value"]}"')
        out.append("    provided: true")
        out.append(f'    source: "{c["source"]}"')
        out.append("    provenance: sourced")
        out.append(f"    via: {c['via']}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Reorganize provided material into a typed inputs ledger.")
    ap.add_argument("--csv", action="append", help="a pasted/exported KPI table (repeatable)")
    ap.add_argument("--series", help="a series store JSON (the prior instance's data)")
    ap.add_argument("--out", help="output path for the YAML inputs fragment (default: stdout)")
    args = ap.parse_args()
    if not args.csv and not args.series:
        ap.error("provide at least one source: --csv and/or --series")

    ledger, prov = reorganize(args.csv, args.series)
    text = emit_yaml(ledger)
    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print(f"intake: OK — {len(ledger)} sourced cells -> {args.out} "
              f"({prov['overridden']} deduped, {prov['gap_filled']} from prior instance)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
